### ISSUE TITLE
Flasgger cannot be installed

### ISSUE THREAD

**Issue by Latin1** [David-OConnor/pyflow#25] opened 2019-10-21 04:28 UTC
$ pyflow install flasgger
Found lockfile
Resolving dependencies...
Can't find a compatible package for Req { name: "jsonschema", constraints: [Constraint { type_: Lt, version: 3.0.0 }], extra: None, sys_platform: None, python_version: None, install_with_extras: None, path: None, git: None }

**Comment by David-OConnor** [comment] 2019-10-21 06:34
Bug: This is caused by `jsonschema` being specified twice in `flasgger`'s requirements, using `or` logic, while pyflow was expecting it to be on the same line. Standby for a fix.

**Comment by David-OConnor** [comment] 2019-10-21 06:41
In the meanwhile, you can change `flasgger`'s version to one that doesn't do this, ie anything but `0.9.3`. To do this, edit the line in `pyproject.toml` to read `flasgger = "0.9.2"`

**Comment by David-OConnor** [comment] 2019-10-21 08:31
Fixed in latest commit.

**Comment by Latin1** [comment] 2019-10-22 01:41
Thanks

**Closed** 2019-10-22 01:41 UTC
Labels: bug
