### ISSUE TITLE
`pyflow script`: filename is mangled

### ISSUE THREAD

**Issue by madig** [David-OConnor/pyflow#37] opened 2019-12-13 22:43 UTC
1. Be on git master
2. Make a script `a.py`:
```Python
__requires__ = ["fonttools[ufo]"]

import fontTools.ufoLib
```
3. `pyflow script a.py`

```
thread 'main' panicked at 'Problem opening the Python script file.: Os { code: 2, kind: NotFound, message: "No such file or directory" }', src/libcore/result.rs:1165:5
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace.
```

`println!`-debugging reveals `filename` in main.rs:970 to be "a_py". Looks like someone stepped on the dot.

**Comment by David-OConnor** [comment] 2019-12-14 04:46
There are two separate bugs here:
- The bug with filename mangling, caused by inappropriately applying a filename standardization - fixed in the latest commit.
- Extras are currently broken for scripts like this, which I need to fix.

You can work around this by specifying dependencies from extras manually, eg:
```python
__requires__ = ["fonttools" ,"fs"]

import fontTools.ufoLib
```

**Comment by David-OConnor** [comment] 2019-12-21 02:48
First bug fixed in latest release.

**Comment by madig** [comment] 2019-12-21 15:55
It werks :+1:

**Comment by ElijahSink** [comment] 2020-10-29 19:50
If this bug was fixed, the issue can be closed, no?

**Comment by David-OConnor** [comment] 2020-10-29 19:53
Good point

**Closed** 2020-10-29 19:53 UTC
Labels: bug
