### ISSUE TITLE
Error installing jupyterlab

### ISSUE THREAD

**Issue by vishrawas** [David-OConnor/pyflow#108] opened 2021-05-08 04:40 UTC
Trying to install JupyterLab and receiving the following error:

```thread 'main' panicked at 'Problem creating renamed path: AliasError { details: "Timed out attempting to create a directory" }', /Users/<username>/.cargo/registry/src/github.com-1ecc6299db9ec823/pyflow-0.2.9/src/main.rs:794:58```
I got the same error in my both Mac and Manjaro machine.

The way to reproduce:
1. pyflow new test
2. cd test
3. pyenv local 3.8.2
4. pyflow install jupyterlab

I am able to install other packages.

Strangely, once I encounter the above error, executing any`pyflow install` throws the following error:
``` pyflow install humanize```
```Can't find a compatible package for Req { name: "jupyter-server", constraints: [Constraint { type_: Exact, version: 1.5.1 }], extra: None, sys_platform: None, python_version: None, install_with_extras: None, path: None, git: None }```

The only option I have is to delete the folder and start again. 

The detailed log is  as follows:
```
thread 'main' panicked at 'Problem creating renamed path: AliasError { details: "Timed out attempting to create a directory" }', /home/<username>/.cargo/registry/src/github.com-1ecc6299db9ec823/pyflow-0.2.9/src/main.rs:794:58
stack backtrace:
   0:     0x55b1a3476fc0 - std::backtrace_rs::backtrace::libunwind::trace::h38f496e2f60ff056
                               at /build/rust/src/rustc-1.51.0-src/library/std/src/../../backtrace/src/backtrace/libunwind.rs:90:5
   1:     0x55b1a3476fc0 - std::backtrace_rs::backtrace::trace_unsynchronized::h56106da60d2adf4e
                               at /build/rust/src/rustc-1.51.0-src/library/std/src/../../backtrace/src/backtrace/mod.rs:66:5
   2:     0x55b1a3476fc0 - std::sys_common::backtrace::_print_fmt::he96612ccef88d499
                               at /build/rust/src/rustc-1.51.0-src/library/std/src/sys_common/backtrace.rs:67:5
   3:     0x55b1a3476fc0 - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::h7bc9abcb54e035e8
                               at /build/rust/src/rustc-1.51.0-src/library/std/src/sys_common/backtrace.rs:46:22
   4:     0x55b1a349c6ec - core::fmt::write::hc902605fce7cd9d0
                               at /build/rust/src/rustc-1.51.0-src/library/core/src/fmt/mod.rs:1096:17
   5:     0x55b1a346eea5 - std::io::Write::write_fmt::hc1b61b7b2ff05b80
                               at /build/rust/src/rustc-1.51.0-src/library/std/src/io/mod.rs:1568:15
   6:     0x55b1a3479545 - std::sys_common::backtrace::_print::hbfdf09e2f4163e71
                               at /build/rust/src/rustc-1.51.0-src/library/std/src/sys_common/backtrace.rs:49:5
   7:     0x55b1a3479545 - std::sys_common::backtrace::print::h0f74697e38abc595
                               at /build/rust/src/rustc-1.51.0-src/library/std/src/sys_common/backtrace.rs:36:9
   8:     0x55b1a3479545 - std::panicking::default_hook::{{closure}}::hddc95caf81a22541
                               at /build/rust/src/rustc-1.51.0-src/library/std/src/panicking.rs:208:50
   9:     0x55b1a34790a3 - std::panicking::default_hook::h3eba1f2638a2c835
                               at /build/rust/src/rustc-1.51.0-src/library/std/src/panicking.rs:225:9
  10:     0x55b1a3479ce1 - std::panicking::rust_panic_with_hook::h8f88f1391abedf2a
                               at /build/rust/src/rustc-1.51.0-src/library/std/src/panicking.rs:591:17
  11:     0x55b1a3479827 - std::panicking::begin_panic_handler::{{closure}}::hf473b53e26f56dd7
                               at /build/rust/src/rustc-1.51.0-src/library/std/src/panicking.rs:497:13
  12:     0x55b1a347745c - std::sys_common::backtrace::__rust_end_short_backtrace::h6fde4603ccb02286
                               at /build/rust/src/rustc-1.51.0-src/library/std/src/sys_common/backtrace.rs:141:18
  13:     0x55b1a3479789 - rust_begin_unwind
                               at /build/rust/src/rustc-1.51.0-src/library/std/src/panicking.rs:493:5
  14:     0x55b1a349b081 - core::panicking::panic_fmt::hac8c69602870cdf7
                               at /build/rust/src/rustc-1.51.0-src/library/core/src/panicking.rs:92:14
  15:     0x55b1a349aea3 - core::option::expect_none_failed::h7dfb96068fc9393b
                               at /build/rust/src/rustc-1.51.0-src/library/core/src/option.rs:1300:5
  16:     0x55b1a30fc1eb - pyflow::sync::h18ae6282611a06a1
  17:     0x55b1a3105950 - pyflow::main::ha4fd5b6d8d9d500c
  18:     0x55b1a3109d53 - std::sys_common::backtrace::__rust_begin_short_backtrace::hbfe38066b3db6f54
  19:     0x55b1a3120439 - std::rt::lang_start::{{closure}}::h344b9e40964d9259
  20:     0x55b1a347a107 - core::ops::function::impls::<impl core::ops::function::FnOnce<A> for &F>::call_once::h6646ba386ff34dbe
                               at /build/rust/src/rustc-1.51.0-src/library/core/src/ops/function.rs:259:13
  21:     0x55b1a347a107 - std::panicking::try::do_call::h47e376e14a330979
                               at /build/rust/src/rustc-1.51.0-src/library/std/src/panicking.rs:379:40
  22:     0x55b1a347a107 - std::panicking::try::hb7ef6d6b3d4db346
                               at /build/rust/src/rustc-1.51.0-src/library/std/src/panicking.rs:343:19
  23:     0x55b1a347a107 - std::panic::catch_unwind::h534d7ac891813066
                               at /build/rust/src/rustc-1.51.0-src/library/std/src/panic.rs:431:14
  24:     0x55b1a347a107 - std::rt::lang_start_internal::h8191eeb0dbee8736
                               at /build/rust/src/rustc-1.51.0-src/library/std/src/rt.rs:51:25
  25:     0x55b1a3109d22 - main
  26:     0x7fe838880b25 - __libc_start_main
  27:     0x55b1a305d0ae - _start
  28:                0x0 - <unknown>
```

**Comment by tanj** [comment] 2021-05-23 02:05
The second part of this is happening because `jupyterlab` gets added to pyproject.toml even though it fails to install.

Same workaround as in https://github.com/David-OConnor/pyflow/issues/72#issuecomment-646310677

**Comment by tsuga** [comment] 2021-06-01 00:51
Is there any workaround for the first part?

**Comment by tanj** [comment] 2021-06-01 05:37
I thought I had an idea for a work around, but ran into an issue with getting a wheel to build. (both windows and linux, but different packages for both) I'll poke around this week and see what I can discover.

I think the initial error is caused by having two different `Tidle` deps for jupyterlab-server.

```
"jupyterlab-server (~=2.3)"
"jupyterlab-server[test] (~=2.2) ; extra == 'test'"
```

This is my first look into the dep resolution code, so not sure.

**Comment by tanj** [comment] 2021-06-18 00:29
The dependency resolution part of this bug seems to be fixed as of 0487bca799f2891f943ae4d5c90c4650f7ab4de6

Hit the same bug as in #118 
`ValueError: ZIP does not support timestamps before 1980`
when trying to install `pytest_console_scripts`

**Comment by David-OConnor** [comment] 2021-06-18 21:29
Fixed in repo

**Closed by David-OConnor** 2021-06-18 21:29 UTC
Labels: bug
