### ISSUE TITLE
Fails to run on mac

### ISSUE THREAD

**Issue by alok** [David-OConnor/pyflow#13] opened 2019-10-03 23:41 UTC
I installed with cargo from the master branch. When I run `pyflow install numpy` after entering a directory created with `pyflow new projectname`, I get (with `RUST_BACTRACE=full`):

```text
🐍Setting up Python environment...
thread 'main' panicked at 'Problem creating lib directory: Os { code: 2, kind: NotFound, message: "No such file or directory" }', src/libcore/result.rs:1165:5
stack backtrace:
   0:        0x10d0ff995 - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::h458d13cb63d0c050
   1:        0x10d1259e0 - core::fmt::write::h53670af22ec3875f
   2:        0x10d0fa08b - std::io::Write::write_fmt::haf3d8737b9e851a5
   3:        0x10d101c8a - std::panicking::default_hook::{{closure}}::h3fbc052481cb023f
   4:        0x10d101995 - std::panicking::default_hook::h47b52fdc388b3b91
   5:        0x10d102357 - std::panicking::rust_panic_with_hook::he9c773346a268707
   6:        0x10d101ecd - std::panicking::continue_panic_fmt::h6ce88923515447fe
   7:        0x10d101e29 - rust_begin_unwind
   8:        0x10d13b59f - core::panicking::panic_fmt::h374d7a5fcdeaf2cf
   9:        0x10d13b679 - core::result::unwrap_failed::hdf38bf4ba53b175b
  10:        0x10cd74fb4 - pyflow::install::download_and_install_package::h962f28ab57bd4aee
  11:        0x10cd69612 - pyflow::py_versions::create_venv::hcb44ecfaa27a005d
  12:        0x10cd05525 - pyflow::util::find_venv_info::hb763c03c66689fc0
  13:        0x10cd45d58 - pyflow::main::hdf0794e46e104969
  14:        0x10cd29536 - std::rt::lang_start::{{closure}}::h26547f149e205262
  15:        0x10d101da8 - std::panicking::try::do_call::h1875c1f8f5700dda
  16:        0x10d10aaef - __rust_maybe_catch_panic
  17:        0x10d1027be - std::rt::lang_start_internal::h5206fcf99580d1b5
  18:        0x10cd4c699 - main

```

**Comment by David-OConnor** [comment] 2019-10-04 02:14
This is likely due to incorrect assumptions I made about the directory structure on Mac.

Could you please:
- Post the directory structure Pyflow built inside `__pypackages__` ?
- If able, add the line `println!("Lib path: {:?}", lib_path)` at the top of the `download_and_install_package` function in `src/install` , rebuild and rerun, and report what it outputs?

I'm suspicious there are other issues related to directories on Mac that you'll run across once this is sorted.

**Comment by alok** [comment] 2019-10-04 02:45
Directory structure:
```
.
└── 3.7
    ├── .venv
    │   ├── bin
    │   ├── include
    │   └── lib
    │       └── python3.7
    │           └── site-packages
    │               ├── __pycache__
    │               ├── pip
    │               │   ├── __pycache__
    │               │   ├── _internal
    │               │   │   ├── __pycache__
    │               │   │   ├── cli
    │               │   │   │   └── __pycache__
    │               │   │   ├── commands
    │               │   │   │   └── __pycache__
    │               │   │   ├── models
    │               │   │   │   └── __pycache__
    │               │   │   ├── operations
    │               │   │   │   └── __pycache__
    │               │   │   ├── req
    │               │   │   │   └── __pycache__
    │               │   │   ├── utils
    │               │   │   │   └── __pycache__
    │               │   │   └── vcs
    │               │   │       └── __pycache__
    │               │   └── _vendor
    │               │       ├── __pycache__
    │               │       ├── cachecontrol
    │               │       │   ├── __pycache__
    │               │       │   └── caches
    │               │       │       └── __pycache__
    │               │       ├── certifi
    │               │       │   └── __pycache__
    │               │       ├── chardet
    │               │       │   ├── __pycache__
    │               │       │   └── cli
    │               │       │       └── __pycache__
    │               │       ├── colorama
    │               │       │   └── __pycache__
    │               │       ├── distlib
    │               │       │   ├── __pycache__
    │               │       │   └── _backport
    │               │       │       └── __pycache__
    │               │       ├── html5lib
    │               │       │   ├── __pycache__
    │               │       │   ├── _trie
    │               │       │   │   └── __pycache__
    │               │       │   ├── filters
    │               │       │   │   └── __pycache__
    │               │       │   ├── treeadapters
    │               │       │   │   └── __pycache__
    │               │       │   ├── treebuilders
    │               │       │   │   └── __pycache__
    │               │       │   └── treewalkers
    │               │       │       └── __pycache__
    │               │       ├── idna
    │               │       │   └── __pycache__
    │               │       ├── lockfile
    │               │       │   └── __pycache__
    │               │       ├── msgpack
    │               │       │   └── __pycache__
    │               │       ├── packaging
    │               │       │   └── __pycache__
    │               │       ├── pep517
    │               │       │   └── __pycache__
    │               │       ├── pkg_resources
    │               │       │   └── __pycache__
    │               │       ├── progress
    │               │       │   └── __pycache__
    │               │       ├── pytoml
    │               │       │   └── __pycache__
    │               │       ├── requests
    │               │       │   └── __pycache__
    │               │       ├── urllib3
    │               │       │   ├── __pycache__
    │               │       │   ├── contrib
    │               │       │   │   ├── __pycache__
    │               │       │   │   └── _securetransport
    │               │       │   │       └── __pycache__
    │               │       │   ├── packages
    │               │       │   │   ├── __pycache__
    │               │       │   │   ├── backports
    │               │       │   │   │   └── __pycache__
    │               │       │   │   └── ssl_match_hostname
    │               │       │   │       └── __pycache__
    │               │       │   └── util
    │               │       │       └── __pycache__
    │               │       └── webencodings
    │               │           └── __pycache__
    │               ├── pip-19.0.3.dist-info
    │               ├── pkg_resources
    │               │   ├── __pycache__
    │               │   ├── _vendor
    │               │   │   ├── __pycache__
    │               │   │   └── packaging
    │               │   │       └── __pycache__
    │               │   └── extern
    │               │       └── __pycache__
    │               ├── setuptools
    │               │   ├── __pycache__
    │               │   ├── _vendor
    │               │   │   ├── __pycache__
    │               │   │   └── packaging
    │               │   │       └── __pycache__
    │               │   ├── command
    │               │   │   └── __pycache__
    │               │   └── extern
    │               │       └── __pycache__
    │               └── setuptools-40.8.0.dist-info
    └── lib

111 directories
```

`lib_path`: $PROJECT_ROOT/__pypackages__/3.7/.venv/lib64/python3.7/site-packages`

**Comment by David-OConnor** [comment] 2019-10-04 03:14
Could you please add the line: `println!("pypackges dir: {:?}",pypackages_dir);` at line `1333` of `src/main.rs`, (Right after it's assigned) and post the result? I'm not sure why the `__` is being ommitted. It also looks like there's an issue regarding `lib` vs `lib64`. Note that this is being triggered when attempting to install `wheel`, when building the env.

I appologize for asking you to run through these, but I'm not sure how to test on Mac.

**Comment by David-OConnor** [comment] 2019-10-04 03:25
Nvm: The problem is `lib` vs `lib64`; I misinterpreted GH's formatting `__` as bold.

**Comment by alok** [comment] 2019-10-04 03:55
Did that. Now I don't get that error and it creates a lockfile, but the lockfile is empty and no packages are actually downloaded (numpy in this case).

**Comment by alok** [comment] 2019-10-04 03:57
Here's the lockfile:

```
package = []

[metadata]

```

**Comment by David-OConnor** [comment] 2019-10-04 04:04
Could you please post the contents of `[tool.pyflow.dependencies]` in `pyproject.toml` ?

**Comment by alok** [comment] 2019-10-04 04:05
```
# See PEP 518: https://www.python.org/dev/peps/pep-0518/ for info on this file's structure.

[tool.pyflow]
name = ""
py_version = "3.7"
version = "0.1.0"
author = ""


[tool.pyflow.scripts]


[tool.pyflow.dependencies]
numpy = "^1.17.2"


[tool.pyflow.dev-dependencies]


```

**Comment by David-OConnor** [comment] 2019-10-04 04:07
Thank you. Could you run `pyflow reset`, and try again?

**Comment by alok** [comment] 2019-10-04 04:09
Same issue.

**Comment by David-OConnor** [comment] 2019-10-04 04:28
This may be related to a broken commit I pushed last night:

Can you please remove this chunk of code in `src/main.rs`, at line 1141, and try again? 
```rust
combined_reqs = combined_reqs
        .into_iter()
        .filter(|r| r.git.is_some())
        .collect();
```

**Comment by alok** [comment] 2019-10-04 04:47
Looks like that's it. I was able to install after deleting that.

**Comment by David-OConnor** [comment] 2019-10-04 12:04
Fixed in latest commit.

**Comment by David-OConnor** [comment] 2019-10-05 08:52
Released

**Closed by David-OConnor** 2019-10-05 08:52 UTC
Labels: bug
