### ISSUE TITLE
Use of Uvicorn

### ISSUE THREAD

**Issue by danielloader** [David-OConnor/pyflow#7] opened 2019-09-20 19:39 UTC
I've started a new package, installed uvicorn and fastapi and put the following in main.py:

```
from fastapi import FastAPI

app = FastAPI()


@app.get("/")
def read_root():
    return {"Hello": "World"}


@app.get("/items/{item_id}")
def read_item(item_id: int, q: str = None):
    return {"item_id": item_id, "q": q}
```

Trying to run this with `pyflow python uvicorn package:main`,`pyflow uvicorn package:main` doesn't work, can you clarify the syntax for running servers like `gunicorn`, `uvicorn` or `hypercorn`?

https://github.com/tiangolo/fastapi#example
Thanks

**Comment by David-OConnor** [comment] 2019-09-21 04:57
This is caused by a bug in pyflow, where it's not handling specified dependencies properly in `uvicorn`. Ie it's using a format I hadn't seen before. Will fix soon.

**Comment by David-OConnor** [comment] 2019-09-21 05:15
Second issue: There's a problem parsing console scripts that include spaces. Expect a patch soon.

The syntax should be: `pyflow gunicorn`.

**Comment by David-OConnor** [comment] 2019-09-21 08:24
Fixed on Pyflow's end. Try [0.1.1](https://github.com/David-OConnor/pyflow/releases/tag/0.1.1).

There's still a (subtle) problem on the dependency cache, where it works on my computer, but fails deployed. I've updated it for those two packages, so your use case will now work, but there's still something wrong; possibly the server timing out before done caching.

**Comment by David-OConnor** [comment] 2019-09-24 09:36
Fixed on Pydeps` end. If this works for you, I'm prepared to close this.

**Closed** 2019-09-26 02:13 UTC
Labels: bug
